### ISSUE TITLE
Installing for production

### ISSUE THREAD

**Issue by qharlie** [cadorn/ace-extjs#3]
The install guide references a commonjs binary, however I can find this anywhere ?  

How do I install it ?

**Comment by cadorn** [comment]
See: https://github.com/pinf/loader-js/blob/master/docs/Setup.md

**Comment by qharlie** [comment]
Great thanks!  It seems to be looking in the root directory for main.js

http://localhost/extjs4-ace/Component/3811E0B2D30557A03C7171B8F7D26B8A@/main.js

However I'm a subdirectory,

http://localhost/bang/www/

How do I tell it to look there ?  If i add those subdirectories to that url it does indeed exist

**Comment by cadorn** [comment]
The following should work:

```
<script type="text/javascript">
    bravojs = {
        url: window.location.protocol + "//" + window.location.host + "/bang/www/extjs4-ace/Component.js"
    };
    document.write('<script type="text/javascript" src="' + bravojs.url + '"><' + '/script>');
</script>
```
