### ISSUE TITLE
Wow..

### ISSUE THREAD

**Issue by vmadman** [cadorn/ace-extjs#7]
Yeah, why can't I just download the source and embed it in my application?  What's all of this Node.js and PINF crap?  Why would you do that, is it your goal to provide a component for 2% of the people who could use it?  Must be some sort of exclusive club, like Mensa.. wow..

**Comment by cadorn** [comment]
This is an experimental prototype (Status: alpha). I'll be updating it to use newer versions of NodeJS + PINF in time. This will make it easier to use and you may upgrade your opinion from crap to shit.

Feel free to write and publish your own integration. Nobody is stopping you.
